In [1]:
import numpy as np
rng = np.random.RandomState(123)

d = 2 #데이터 차원
N = 10 #각 패턴마다의 데이터 수
mean = 5 #뉴런이 발화하는 데이터의 평균값

x1 = rng.randn(N, d) + np.array([0, 0])
x2 = rng.randn(N, d) + np.array([mean, mean])

In [2]:
x1

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 ],
       [-0.67888615, -0.09470897],
       [ 1.49138963, -0.638902  ],
       [-0.44398196, -0.43435128],
       [ 2.20593008,  2.18678609],
       [ 1.0040539 ,  0.3861864 ]])

In [3]:
x2

array([[5.73736858, 6.49073203],
       [4.06416613, 6.17582904],
       [3.74611933, 4.3622485 ],
       [5.9071052 , 3.5713193 ],
       [4.85993128, 4.1382451 ],
       [4.74438063, 2.20141089],
       [3.2284669 , 4.30012277],
       [5.92746243, 4.82636432],
       [5.00284592, 5.68822271],
       [4.12046366, 5.28362732]])

In [4]:
x = np.concatenate((x1, x2), axis=0)
x

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 ],
       [-0.67888615, -0.09470897],
       [ 1.49138963, -0.638902  ],
       [-0.44398196, -0.43435128],
       [ 2.20593008,  2.18678609],
       [ 1.0040539 ,  0.3861864 ],
       [ 5.73736858,  6.49073203],
       [ 4.06416613,  6.17582904],
       [ 3.74611933,  4.3622485 ],
       [ 5.9071052 ,  3.5713193 ],
       [ 4.85993128,  4.1382451 ],
       [ 4.74438063,  2.20141089],
       [ 3.2284669 ,  4.30012277],
       [ 5.92746243,  4.82636432],
       [ 5.00284592,  5.68822271],
       [ 4.12046366,  5.28362732]])

In [7]:
# 웨이트벡터와 바이어스 초기화해주기
w = np.zeros(d)
b = 0

In [8]:
# 출력식 정의
def y(x):
    return step(np.dot(w, x) + b)
def step(x):
    return 1 * (x > 0)

# 처음 정의한 10개는 뉴런이 발화하지 않는 데이터
def t(i):
    if i < N:
        return 0
    else:
        return 1

In [10]:
while True:
    classified = True
    for i in range(N*2):
        delta_w = (t(i)-y(x[i])) * x[i]
        delta_b = (t(i)-y(x[i]))
        w += delta_w
        b += delta_b
        classified *= all(delta_w == 0)*(delta_b == 0)
    if classified:
        break

In [11]:
print("w : {}, b : {}".format(w, b))

w : [2.14037745 1.2763927 ], b : -9
