In [9]:
import numpy as np
import tensorflow as tf

In [10]:
# 웨이트와 바이어스 초기화
w = tf.Variable(tf.zeros([2, 1])) # 2차원
b = tf.Variable(tf.zeros([1]))

In [11]:
# 수식 정의하기
def y(x):
    return sigmoid(np.dot(w, x) + b)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [12]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x = tf.placeholder(tf.float32, shape=[None, 2])
t = tf.placeholder(tf.float32, shape=[None, 1])

tf.disable_v2_behavior()
y = tf.nn.sigmoid(tf.matmul(x, w) + b) # matmul은 행렬곱

In [13]:
# 오차함수 구현해두기
cross_entropy = -tf.reduce_sum(t*tf.log(y) + (1-t)*tf.log(1-y))

In [14]:
# 경사하강법 구현하기
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy)

In [15]:
# 뉴런의 발화여부 정하는 기준~~
correct_prediction = tf.equal(tf.to_float(tf.greater(y, 0.5)), t)

Instructions for updating:
Use `tf.cast` instead.


In [16]:
# 학습용 데이터 만들기
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [1]])

In [17]:
# 텐서플로에서는 데이터를 취급하는 방법인 세션이라는 것 안에서 계산 실행~~
tf.disable_v2_behavior()
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init) # 모델을 정의할 때 선언했던 변수와 식을 초기화하는 것~

In [18]:
# 학습 구현해보기
for epoch in range(200):
    sess.run(train_step, feed_dict={
        x: X, t: Y
    })

In [19]:
# 적절히 분류한 것들 보기
classified = correct_prediction.eval(session=sess, feed_dict={x : X, t : Y})
classified

array([[ True],
       [ True],
       [ True],
       [ True]])

In [20]:
# 각 입력에 대한 출력 확률 보기
prob = y.eval(session=sess, feed_dict={x:X, t:Y})
prob

array([[0.22355038],
       [0.9142595 ],
       [0.9142595 ],
       [0.99747425]], dtype=float32)

In [21]:
# tf.Variable()로 정의한 변수의 값은 .eval이 아니라 sess.run()으로 구할 수 있음
print('w :',sess.run(w))
print('b :', sess.run(b))

w : [[3.6118844]
 [3.6118844]]
b : [-1.245095]


#### 이번에는 Keras로 구현해보기

In [22]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

model = Sequential([Dense(input_dim=2, units=1), Activation('sigmoid')])

In [23]:
# 경사하강법 구현
model.compile(loss='binary_crossentropy', optimizer=SGD(lr=0.1))

C:\Users\Main\Anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


In [24]:
# 학습용 데이터 만들기
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [1]])

In [25]:
# 학습하기
model.fit(X, Y, epochs=200, batch_size=1)

Train on 4 samples
Epoch 1/200
4/4 [==============================] - 2s 5ms/sample - loss: 1.2510
Epoch 2/200
4/4 [==============================] - 0s 5ms/sample - loss: 1.0771
Epoch 3/200
4/4 [==============================] - 0s 5ms/sample - loss: 0.9426
Epoch 4/200
4/4 [==============================] - 0s 5ms/sample - loss: 0.8396
Epoch 5/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.7598
Epoch 6/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.6992
Epoch 7/200
4/4 [==============================] - 0s 5ms/sample - loss: 0.6540
Epoch 8/200
4/4 [==============================] - 0s 5ms/sample - loss: 0.6202
Epoch 9/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.5925
Epoch 10/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.5706
Epoch 11/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.5521
Epoch 12/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.5363
Epoch 13/200
4/4 [

Epoch 102/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.2045
Epoch 103/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.2030
Epoch 104/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.2016
Epoch 105/200
4/4 [==============================] - 0s 5ms/sample - loss: 0.2002
Epoch 106/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.1988
Epoch 107/200
4/4 [==============================] - 0s 3ms/sample - loss: 0.1974
Epoch 108/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.1960
Epoch 109/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.1947
Epoch 110/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.1933
Epoch 111/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.1920
Epoch 112/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.1907
Epoch 113/200
4/4 [==============================] - 0s 4ms/sample - loss: 0.1894
Epoch 114/200
4/

In [28]:
# 학습 결과 확인해보기
classes = model.predict(X, batch_size=1)
classes

C:\Users\Main\Anaconda3\lib\site-packages\keras\engine\training_v1.py:2067: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


array([[0.23791309],
       [0.9108444 ],
       [0.90755844],
       [0.9968971 ]], dtype=float32)